create table MEMBER (
   ID		 varchar(20) PRIMARY KEY,
   PASSWORD  varchar(50) not null,
   name		 varchar(20) not null,
   birth	 varchar(20) not null,
   address	 varchar(50) not null,
   PHONE     varchar(20) not null,
   EMAIL	 varchar(50)
);
create table MASTER (
   ID		varchar(20)	PRIMARY KEY,
   PASSWORD varchar(50) not null
);
CREATE TABLE NEWS (
    boardNum number(10) primary key,
    ID VARCHAR2(20) REFERENCES MASTER (ID) ,
    title VARCHAR2(100) not null,
    content VARCHAR2(3000) not null,
    pwd VARCHAR2(100) not null,
    fileName VARCHAR2(100),
    oriName VARCHAR2(100),
    WRITE_DATE DATE DEFAULT SYSDATE
);
CREATE TABLE announce (
    boardNum VARCHAR2(20) ,
    ID VARCHAR2(20) REFERENCES MASTER (ID) ,
    title VARCHAR2(100) primary key,
    content VARCHAR2(3000) not null,
    pwd VARCHAR2(100) not null,
    fileName VARCHAR2(100),
    oriName VARCHAR2(100),
    WRITE_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE DECLARE (
    boardNum number(10) primary key,
    ID VARCHAR2(20) REFERENCES member (ID) ON DELETE CASCADE,
    title VARCHAR2(100) not null,
    content VARCHAR2(3000) not null,
    pwd VARCHAR2(100) not null,
    fileName VARCHAR2(100),
    oriName VARCHAR2(100),
    WRITE_DATE DATE DEFAULT SYSDATE
);
CREATE TABLE promotion (
    boardNum number(10) primary key,
    ID VARCHAR2(20) REFERENCES MASTER (ID),
    title VARCHAR2(100) not null,
    content VARCHAR2(3000) not null,
    pwd VARCHAR2(100) not null,
    fileName VARCHAR2(100),
    oriName VARCHAR2(100),
    WRITE_DATE DATE DEFAULT SYSDATE
);
CREATE TABLE E_BOOK (
    boardNum number(10) primary key,
    ID VARCHAR2(20) REFERENCES MASTER (ID),
    title VARCHAR2(100) not null,
    content VARCHAR2(3000) not null,
    pwd VARCHAR2(100) not null,
    fileName VARCHAR2(100),
    oriName VARCHAR2(100),
    WRITE_DATE DATE DEFAULT SYSDATE
);
CREATE TABLE delivery (
    boardNum number(10) primary key,
    NAME VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(50) NOT NULL,
    ADDRESS VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    NOTE VARCHAR2(2000) ,
    WRITE_DATE DATE DEFAULT SYSDATE
);
----------------------------------------------------
CREATE TABLE NATURE ( --자연관광
    BOARDNUM NUMBER(6) PRIMARY KEY,
    TITLE VARCHAR2(150) NOT NULL, --글제목
    CONTAIN VARCHAR2(3000) NOT NULL, --글내용
    FILENAME VARCHAR2(100), --원본파일명
    VIEWNAME1 VARCHAR2(100), --상세보기파일명
    VIEWNAME2 VARCHAR2(100), --상세보기파일명
    VIEWNAME3 VARCHAR2(100), --상세보기파일명
    ADDRESS VARCHAR2(300) NOT NULL, --주소
    PAY VARCHAR2(300) NOT NULL, --이용요금
    PHONE VARCHAR2(100) NOT NULL, --전화번호
    TIME VARCHAR2(300) NOT NULL, --이용시간
    WRITEDATE DATE DEFAULT SYSDATE NOT NULL, --작성일시
    HIT NUMBER(5) --조회수
);

CREATE TABLE CULTURE ( --문화관광
    BOARDNUM NUMBER(6) PRIMARY KEY,
    TITLE VARCHAR2(150) NOT NULL, --글제목
    CONTAIN VARCHAR2(3000) NOT NULL, --글내용
    FILENAME VARCHAR2(100), --원본파일명
    VIEWNAME1 VARCHAR2(100), --상세보기파일명
    VIEWNAME2 VARCHAR2(100), --상세보기파일명
    VIEWNAME3 VARCHAR2(100), --상세보기파일명
    ADDRESS VARCHAR2(300) NOT NULL, --주소
    PAY VARCHAR2(300) NOT NULL, --이용요금
    PHONE VARCHAR2(100) NOT NULL, --전화번호
    TIME VARCHAR2(300) NOT NULL, --이용시간
    WRITEDATE DATE DEFAULT SYSDATE NOT NULL, --작성일시
    HIT NUMBER(5) --조회수
);

CREATE TABLE EXPERIENCE ( --체험관광
    BOARDNUM NUMBER(6) PRIMARY KEY,
    TITLE VARCHAR2(150) NOT NULL, --글제목
    CONTAIN VARCHAR2(3000) NOT NULL, --글내용
    FILENAME VARCHAR2(100), --원본파일명
    VIEWNAME1 VARCHAR2(100), --상세보기파일명
    VIEWNAME2 VARCHAR2(100), --상세보기파일명
    VIEWNAME3 VARCHAR2(100), --상세보기파일명
    ADDRESS VARCHAR2(300) NOT NULL, --주소
    PAY VARCHAR2(300) NOT NULL, --이용요금
    PHONE VARCHAR2(100) NOT NULL, --전화번호
    TIME VARCHAR2(300) NOT NULL, --이용시간
    WRITEDATE DATE DEFAULT SYSDATE NOT NULL, --작성일시
    HIT NUMBER(5) --조회수
);

CREATE TABLE FESTIVAL ( --축제
    BOARDNUM NUMBER(6) PRIMARY KEY,
    MONTH VARCHAR2(10) NOT NULL,
    TITLE VARCHAR2(150) NOT NULL,
    TIME VARCHAR2(300) NOT NULL,
    HOST VARCHAR2(150) NOT NULL,
    ADDRESS VARCHAR2(300) NOT NULL,
    CONTAIN VARCHAR2(3000) NOT NULL,
    FILENAME VARCHAR2(100),
    VIEWNAME1 VARCHAR2(100),
    VIEWNAME2 VARCHAR2(100), 
    VIEWNAME3 VARCHAR2(100),
    INFORMATION VARCHAR2(2000) NOT NULL
);

CREATE TABLE HIDDENSPOT (
    BOARDNUM NUMBER(6) PRIMARY KEY,
    TITLE VARCHAR2(150) NOT NULL,
    WRITER VARCHAR2(100) NOT NULL,
    WRITEDATE DATE DEFAULT SYSDATE NOT NULL,
    FILENAME VARCHAR2(100),
    CONTAIN VARCHAR2(3000) NOT NULL,
    HIT NUMBER(5) NOT NULL
);

create table hiddencomment (
    BOARDNUM NUMBER(6) PRIMARY KEY,
    WRITER VARCHAR2(100),
    PASSWORD  varchar(50),
    CONTAIN VARCHAR2(3000),
    WRITEDATE DATE DEFAULT SYSDATE
); 

CREATE TABLE EDUCATION (
    BOARDNUM NUMBER(6) PRIMARY KEY,
    TITLE VARCHAR2(150),
    FILENAME VARCHAR2(100),
    ORINAME VARCHAR2(100)
);

-----------------------------------------------------
CREATE TABLE INFOMATION(
    INFONUM NUMBER(35) PRIMARY KEY,
    INFO VARCHAR2(3000) NOT NULL,
    CITY VARCHAR2(200) NOT NULL,
    CITYPHONE VARCHAR2(300) NOT NULL,
    ADDRESS VARCHAR2(2000) NOT NULL
);
CREATE TABLE PICCONTEST (
	PIC_NUM NUMBER(6) PRIMARY KEY,
    PICTITLE VARCHAR2(50) NOT NULL,
    PICNAME VARCHAR2(50) NOT NULL,
    PICCONTENT VARCHAR2(1000),
    REGDATE DATE DEFAULT SYSDATE
);
CREATE TABLE TRIPPLAN (
    TRIPNUM VARCHAR2(30) PRIMARY KEY,
    ID VARCHAR2(50),
    TRIPTITLE VARCHAR2(300) NOT NULL,
    REGION VARCHAR2(50),
    TRIPTHEME VARCHAR2(100),
    PURPOSE VARCHAR2(500),
    DAY1 VARCHAR2(2000),
    DAY2 VARCHAR2(2000),
    DAY3 VARCHAR2(2000),
    REGDATE DATE DEFAULT SYSDATE
);


CREATE SEQUENCE TRIP_SEQ NOCACHE;
CREATE SEQUENCE PIC_NUM NOCACHE;
CREATE SEQUENCE INF_NUM NOCACHE;

--------------------------------------------------------------------------
CREATE TABLE ZZIM 
(
  ID VARCHAR2(30 BYTE) 
, BOARDNAME VARCHAR2(50 BYTE) 
, TITLE VARCHAR2(1000 BYTE) 
, IMAGE VARCHAR2(100 BYTE) 
, REGDATE DATE DEFAULT SYSDATE 
, IDX NUMBER(20, 0) 
, BOARDIDX NUMBER(20, 0) 
) ;


CREATE TABLE THEMETRAVEL 
(
  IDX NUMBER(10, 0) PRIMARY KEY 
, ID VARCHAR2(30 BYTE) NOT NULL 
, TITLE VARCHAR2(1000 BYTE) NOT NULL 
, INTRO VARCHAR2(4000 BYTE) 
, REGDATE DATE DEFAULT SYSDATE 
, IMAGE1 VARCHAR2(100 BYTE) 
, IMAGE2 VARCHAR2(100 BYTE) 
, IMAGE3 VARCHAR2(100 BYTE) 
, IMAGE4 VARCHAR2(100 BYTE) 
, IMAGE5 VARCHAR2(100 BYTE) 
, PLACENAME1 VARCHAR2(100 BYTE) 
, PLACENAME2 VARCHAR2(100 BYTE) 
, PLACENAME3 VARCHAR2(100 BYTE) 
, PLACENAME4 VARCHAR2(100 BYTE) 
, PLACENAME5 VARCHAR2(100 BYTE) 
, DETAIL1 VARCHAR2(4000 BYTE) 
, DETAIL2 VARCHAR2(4000 BYTE) 
, DETAIL3 VARCHAR2(4000 BYTE) 
, DETAIL4 VARCHAR2(4000 BYTE) 
, DETAIL5 VARCHAR2(4000 BYTE)  
  );




CREATE TABLE REVIEW 
(
  IDX NUMBER(10, 0) PRIMARY KEY 
, ID VARCHAR2(30 BYTE) NOT NULL 
, TITLE VARCHAR2(1000 BYTE) NOT NULL 
, CONTENT VARCHAR2(4000 BYTE) NOT NULL 
, REGDATE DATE DEFAULT SYSDATE 
, IMAGE1 VARCHAR2(100 BYTE) 
, IMAGE2 VARCHAR2(100 BYTE) 
, IMAGE3 VARCHAR2(100 BYTE)  
  );



CREATE TABLE COURSE 
(
  IDX NUMBER(10, 0) PRIMARY KEY 
, ID VARCHAR2(30 BYTE) NOT NULL 
, TITLE VARCHAR2(1000 BYTE) NOT NULL 
, INTRO VARCHAR2(4000 BYTE) NOT NULL 
, REGDATE DATE DEFAULT SYSDATE 
, IMAGE VARCHAR2(100 BYTE) 
, TDAY VARCHAR2(10 BYTE) NOT NULL 
, DAY1 VARCHAR2(1000 BYTE) 
, DAY2 VARCHAR2(1000 BYTE) 
, DAY3 VARCHAR2(1000 BYTE) 
, PLACENAME VARCHAR2(200 BYTE) 
, PLACELA VARCHAR2(200 BYTE) 
, PLACEMA VARCHAR2(200 BYTE) 
);

CREATE SEQUENCE THEMETRAVEL_SEQ NOCACHE;
CREATE SEQUENCE REVIEW_SEQ NOCACHE;
CREATE SEQUENCE COURSE_SEQ NOCACHE;
CREATE SEQUENCE ZZIM_SEQ NOCACHE;

---------------------------------------------------------------------------------------
